import type { FlowStageSpec } from '../types/FlowStageSpec'

// Spec 3.3 as data (D3, D4, D13). Policies: 172_800_000 is 2 days,
// 259_200_000 is 3 days, 604_800_000 is 7 days.
export const FLOW_STAGES: readonly FlowStageSpec[] = [
  {
    id: 'archive',
    component: 'atrium',
    backlog: null,
    metrics: ['atrium.records'],
    pending: [],
    fresh: 'atrium.archive',
    policyMs: 'refresh2x',
  },
  {
    id: 'episodes',
    component: 'atrium',
    backlog: null,
    metrics: [],
    pending: [],
    fresh: 'label',
    policyMs: 172_800_000,
  },
  {
    id: 'synthesis',
    component: 'atrium',
    backlog: 'atrium.synth_deferred',
    metrics: [
      'atrium.synth_synthesized',
      'atrium.synth_deferred',
      'atrium.synth_failed',
    ],
    pending: [],
    fresh: 'atrium.synthesis',
    policyMs: 172_800_000,
  },
  {
    id: 'clips',
    component: 'clips',
    backlog: 'clips.pending',
    metrics: [
      'clips.pending',
      'clips.needs_claude',
      'clips.intake_today',
      'capture.undrained',
    ],
    pending: ['clips.pending', 'clips.needs_claude', 'capture.undrained'],
    fresh: 'oldest_pending',
    policyMs: 604_800_000,
  },
  {
    id: 'curation',
    component: 'atrium',
    backlog: null,
    metrics: [],
    pending: [],
    fresh: 'label',
    policyMs: 604_800_000,
  },
  {
    id: 'brain',
    component: 'brain',
    backlog: 'brain.lint_issues',
    metrics: ['brain.pages', 'brain.lint_issues', 'brain.doctor_failing'],
    pending: ['brain.lint_issues'],
    fresh: 'label',
    policyMs: 172_800_000,
  },
  {
    id: 'index',
    component: 'atrium',
    backlog: 'atrium.not_indexed',
    metrics: ['atrium.records', 'atrium.not_indexed'],
    pending: ['atrium.not_indexed'],
    fresh: 'atrium.refresh',
    policyMs: 'refresh2x',
  },
  {
    id: 'retrieval',
    component: 'atrium',
    backlog: null,
    metrics: [],
    pending: [],
    fresh: 'atrium.content',
    policyMs: 259_200_000,
  },
]
