export const fakeJob = (id: string, state = 'failed') => ({
  id,
  queue: 'queue.demo',
  producer: 'demo',
  state,
  privacy: id === 'job-secret' ? 'secret' : 'internal',
  tier: 'fast',
  created: 1_790_000_000,
  updated: 1_790_000_100,
  attempts: 1,
  last_error: state === 'failed' ? 'timeout' : null,
  acked: null,
  retry_of: null,
  sampling: false,
  kind: 'inference',
  model: 'model-demo',
  priority: 50,
  finished: state === 'failed' ? 1_790_000_002 : null,
  deadline: null,
  lease_node: state === 'running' ? 'node-demo' : null,
  lease_expires: state === 'running' ? 1_790_000_900 : null,
  parent_id: null,
  preemptions: 0,
  tokens_in: 2,
  tokens_out: 3,
  cost_usd: 0,
  wall_s: 1.5,
  last_model: 'model-demo',
  last_provider: 'agy',
  last_started: 1_790_000_001,
  last_outcome: state === 'running' ? null : 'failed',
})
