export const ACTIVITY_LABELS = {
  heading: 'Activity',
  chart: 'Production attempts per bucket by provider',
  chartHint: 'Hover, tap or use the arrow keys for a bucket’s detail.',
  loading: 'Reading the activity…',
  unavailable: 'Could not read the worker activity.',
  showTable: 'Show table',
  time: 'Time',
  attempts: 'Attempts',
  failed: 'failed',
  failedHeader: 'Failed',
  sampling: 'sampling',
  samplingHeader: 'Sampling',
  mean: 'mean',
  meanHeader: 'Mean time',
  outcomes: 'Outcomes',
  providers: 'Providers',
  errors: 'Errors',
  tokens: 'Tokens',
  tokensIn: 'in',
  tokensOut: 'out',
  none: 'none',
  noActivity: 'No production attempts in this range.',
  succeeded: 'succeeded',
  sparkline: 'succeeded attempts per bucket',
  openrouter: 'OpenRouter attempts today (UTC)',
  openrouterTrend: 'OpenRouter attempts per bucket today',
  failuresChart: 'Production failures per bucket by error code',
  failuresIn: 'production failures in the range',
  details: 'details',
} as const
