export const ATRIUM_LABELS = {
  title: 'Atrium',
  loading: 'loading',
  lastGood: 'Last good data is',
  old: 'old.',
  data: 'Atrium data',
  unavailable: 'Could not read atrium.',
  freshness: 'Freshness',
  archive: 'Archive',
  refresh: 'Index refresh',
  content: 'Newest content',
  written: 'status written',
  ago: 'ago',
  never: 'never',
  within: 'policy',
  sources: 'Records per source',
  records: 'records',
  missing: 'Not in the index',
  model: 'Model',
  intended: 'Intended',
  indexed: 'Indexed',
  notIndexed: 'Missing',
  allIndexed: 'Every population is fully indexed.',
  synthesis: 'Synthesis',
  noPass: 'No synthesis pass has been published yet.',
  trend: 'Synthesized and deferred',
  trendChart: 'Synthesized and deferred per bucket',
  doctor: 'Doctor',
  noDoctor: 'Atrium has not published a doctor result yet.',
  lastPass: 'Last pass',
  noPassLog: 'No pass has been logged yet.',
  passesUnavailable: 'Could not read the pass log.',
  streak: 'in a row ended without succeeding',
  passStates: {
    ok: 'ok',
    timeout: 'time box',
    killed: 'killed at the time box',
    failed: 'failed',
    interrupted: 'no end logged',
    running: 'running',
  },
  recent: 'Recent syntheses',
  recentTable: 'Recent syntheses table',
  recentLoading: 'Reading the registry…',
  recentUnavailable: 'Could not read recent syntheses.',
  noRecent: 'No synthesis records yet.',
  registry: 'records in the registry',
  tokens: 'Tokens per day',
  tokensChart: 'Input and output tokens per day',
  input: 'input',
  output: 'output',
  time: 'Time',
  source: 'Source',
  tokensColumn: 'Tokens in / out',
  duration: 'Duration',
  result: 'Result',
  notRecorded: 'not recorded',
  details: 'Details',
  hideDetails: 'Hide details',
  inputReference: 'Input',
  reveal: 'Reveal title and summary',
  conceal: 'Hide content',
  revealing: 'Loading content…',
  revealFailed: 'Could not reveal content.',
  facts: 'Facts',
  openEnds: 'Open ends',
} as const
