export const ATRIUM_LABELS = {
  title: 'Atrium',
  loading: 'loading',
  lastGood: 'Last good data is',
  old: 'old.',
  data: 'Atrium data',
  unavailable: 'Could not read atrium.',
  freshness: 'Freshness',
  archive: 'Archive',
  refresh: 'Index refresh',
  content: 'Newest content',
  written: 'status written',
  ago: 'ago',
  never: 'never',
  within: 'policy',
  sources: 'Records per source',
  records: 'records',
  missing: 'Not in the index',
  model: 'Model',
  intended: 'Intended',
  indexed: 'Indexed',
  notIndexed: 'Missing',
  allIndexed: 'Every population is fully indexed.',
  synthesis: 'Synthesis',
  noPass: 'No synthesis pass has been published yet.',
  trend: 'Synthesized and deferred',
  trendChart: 'Synthesized and deferred per bucket',
  doctor: 'Doctor',
  noDoctor: 'Atrium has not published a doctor result yet.',
} as const
