// UI strings for the Brain screen (spec 7.5); no page content lives here.
export const BRAIN_LABELS = {
  title: 'Brain',
  loading: 'Loading the graph…',
  unavailable:
    'The brain graph is unavailable. The Brain card on Orbit shows why.',
  graphRegion: 'Graph',
  layingOut: 'Laying out the graph…',
  noWebGl:
    'This browser cannot draw the graph (no WebGL). Every page is in the list below.',
  layoutFailed: 'The graph layout failed. Every page is in the list below.',
  skipped: 'pages not shown: their ids fall outside the safe pattern',
  legend: 'Legend',
  untyped: 'untyped',
  otherTypes: 'other types',
  communities: 'communities; the five largest have their own colours',
  orphan: 'Orphan (no inbound links)',
  selected: 'Selected page',
  showPages: 'Show pages',
  pagesCaption: 'Every page in the graph',
  colPage: 'Page',
  colType: 'Type',
  colLinks: 'Linked pages',
  colOrphan: 'Orphan',
  yes: 'yes',
  no: 'no',
  controls: 'Graph controls',
  filters: 'Filters',
  colorBy: 'Colour by',
  byType: 'Type',
  byCommunity: 'Community',
  highlightOrphans: 'Highlight orphans',
  types: 'Page types',
  view: 'View',
  overview: 'Overview',
  oneStep: '1 step',
  twoSteps: '2 steps',
  threeSteps: '3 steps',
  keysHint:
    'Keys: 1-3 steps around the page, + and - to widen or narrow, 0 or Esc for the overview.',
  groupHint:
    'Each group is a community of linked pages, named by its most linked page and sized by its page count. Select a group to open it.',
  drawing: 'Drawing',
  flat: '2D',
  depth3d: '3D',
  loading3d: 'Loading the 3D view…',
  leaveOut: 'Leave out',
  hideOrphans: 'Orphans',
  maxLinks: 'Pages with more links than',
  noLimit: 'none',
  find: 'Find a page',
  pageRegion: 'Page',
  pageLoading: 'Loading the page…',
  pageMissing: 'This page no longer exists.',
  pageUnavailable: 'The page is unavailable.',
  truncated: 'This page is longer than 1 MiB; the rest is not shown.',
  updated: 'Updated',
  sources: 'Sources',
  outbound: 'Links to',
  inbound: 'Linked from',
  missingTarget: '(missing)',
  clearSelection: 'Clear selection',
  related: 'Related, not linked',
  showRelated: 'Show related pages',
  relatedLoading: 'Scoring related pages…',
  relatedUnavailable: 'Related pages are unavailable.',
  relatedNone: 'No related pages without a link.',
  relatedTotal: 'pairs qualify; the best 50 are listed',
  lint: 'Lint',
  lintNone: 'No lint issues.',
  indexStale: 'The index is stale; run brain index.',
  checksUnavailable: 'Lint and doctor results are unavailable.',
  trend: 'Lint over time',
  trendChart: 'Lint issues and failing checks per bucket',
  palettePages: 'Brain pages',
} as const
