export const CLIPS_LABELS = {
  title: 'Clips',
  data: 'Clips data',
  lastGood: 'Last good data is',
  old: 'old.',
  loading: 'loading',
  unavailable: 'Could not read clips.',
  funnel: 'Funnel',
  funnelHint:
    'Clips in each stage now; bars compare stage sizes, not conversion.',
  funnelList: 'Funnel stages',
  captureLane: 'capture API',
  waiting: 'waiting',
  oldest: 'oldest',
  unmeasuredLanes:
    'The browser clipper and newsletter lanes have no count surface yet.',
  groups: {
    pending: 'pending',
    review: 'need review',
    reconciling: 'in reconciliation',
    reconciled: 'reconciled',
    broken: 'broken',
  },
  intake: 'Intake per day',
  intakeChart: 'Clips captured per day',
  captured: 'captured',
  undated: 'without a capture date',
  oldestWaiting: 'Oldest waiting',
  nothingWaiting: 'Nothing is waiting.',
  unknownAge: 'Age unknown',
  doctor: 'Doctor',
  allPass: 'All checks pass.',
  doctorFailure: 'Doctor reports a failure; check details are unavailable.',
  backlog: 'Backlog',
  backlogChart: 'Pending and needing review per bucket',
  items: 'Clips one by one',
  itemList: 'Clips',
  itemsUnlisted:
    'The engine lists no items: add ["status", "--json", "--items"] to engines.clips.subcommands in orbit.json.',
  stage: 'stage',
  attempts: 'attempts',
  lastRun: 'last run',
  workerJob: 'Worker job',
} as const
