export const FLOW_LABELS = {
  title: 'Memory flow',
  loading: 'loading',
  lastGood: 'Last good data is',
  old: 'old.',
  data: 'Memory flow data',
  unavailable: 'Could not read the memory flow.',
  stages: 'Stages',
  canvas: 'Memory flow diagram',
  close: 'Close',
  freshness: 'Freshness',
  ago: 'ago',
  noInstant: 'no instant measured',
  policy: 'policy',
  label: 'launchd label',
  noLabel: 'No launchd label is registered for this stage.',
  lastRun: 'last run',
  noRun: 'no run observed',
  metrics: 'Metrics',
  pending: 'Pending',
  oldest: 'oldest',
  flowsTo: 'Flows to',
  perHour: 'per hour',
  notMeasured: 'not measured',
} as const
