import type { Metric } from '@orbit/contract'

export const METRIC_LABELS: Record<Metric['key'], string> = {
  'launchd.jobs': 'jobs',
  'launchd.running': 'running',
  'launchd.failing': 'failing',
  'worker.queued': 'queued',
  'worker.live': 'running',
  'worker.failed': 'failed',
  'worker.done_1h': 'done in the last hour',
  'worker.wasted_1h_s': 'wasted in the last hour',
  'worker.cooldowns': 'cooling down',
  'worker.nodes': 'nodes',
  'atrium.records': 'records',
  'atrium.not_indexed': 'not indexed',
  'atrium.synth_synthesized': 'synthesized in the last pass',
  'atrium.synth_deferred': 'deferred by synthesis',
  'atrium.synth_failed': 'failed in synthesis',
  'brain.pages': 'pages',
  'brain.lint_issues': 'lint issues',
  'brain.doctor_failing': 'failing checks',
  'clips.total': 'clips',
  'clips.pending': 'pending',
  'clips.needs_claude': 'need review',
  'clips.intake_today': 'captured today',
  'capture.undrained': 'waiting',
  'pending.open': 'open TODOs',
  'pending.partial': 'partial TODOs',
  'pending.blocked': 'blocked TODOs',
  'synthetic.value': 'value',
}
