export const WORKER_LABELS = {
  title: 'Worker',
  loading: 'Reading the worker…',
  unavailable: 'Could not read the worker.',
  diagnosis: 'Diagnosis',
  nothingWaiting: 'No jobs waiting in any queue.',
  working: 'running,',
  waiting: 'waiting.',
  blockedLead: 'waiting and nothing running right now. Why:',
  doneLastHour: 'done in the last hour.',
  noCause: 'No blocking cause found in the worker status.',
  queues: 'Queues',
  queue: 'Queue',
  queued: 'Queued',
  oldest: 'Oldest',
  failed: 'Failed',
  succeeded: 'Succeeded',
  done1h: 'Done 1h',
  idleQueue: 'idle queue',
  idleQueues: 'idle queues',
  cooldowns: 'Runners cooling down',
  noCooldowns: 'No runner is cooling down.',
  availableIn: 'available in',
  at: 'at',
  nodes: 'Nodes',
  noNodes: 'No node has reported.',
  idleFor: 'idle for',
  lastReport: 'last report',
  ago: 'ago',
  power: 'power',
  pressure: 'pressure',
  resident: 'resident',
  lastRelease: 'last release',
  none: 'none',
  unknown: 'unknown',
  failures: 'Recent failures',
  noFailures: 'No recent failures.',
  failedJobs: 'Failed jobs',
  noError: 'no code',
  job: 'job',
} as const
