export const EVENT_KINDS = [
  'component.down',
  'component.recovered',
  'launchd.exit_changed',
  'launchd.started',
  'launchd.stopped',
  'worker.job_failed',
  'worker.cooldown_started',
  'worker.revealed',
  'worker.action',
  'action.started',
  'action.succeeded',
  'action.failed',
  'synthetic.tick',
] as const
